name: Build

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  BUILD_TYPE: Debug

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the `stream-server` library
      uses: actions/checkout@v3

    - name: Checkout the `atomic-tests` package
      uses: actions/checkout@v3
      with:
        repository: grzegorz-grzeda/atomic-tests
        path: ./lib/atomic-tests

    - name: Checkout the `containers` package
      uses: actions/checkout@v3
      with:
        repository: grzegorz-grzeda/containers
        path: ./lib/containers

    - name: Checkout the `g2labs-log` package
      uses: actions/checkout@v3
      with:
        repository: grzegorz-grzeda/g2labs-log
        path: ./lib/g2labs-log

    - name: Checkout the `audit` package
      uses: actions/checkout@v3
      with:
        repository: grzegorz-grzeda/audit
        path: ./lib/audit

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DATOMIC_TESTS_PERFORM=1

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}} --verbose

